// <auto-generated />
namespace FanMatch.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddMatchLockAndBan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMatchLockAndBan));
        
        string IMigrationMetadata.Id
        {
            get { return "201306131333176_AddMatchLockAndBan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
