// <auto-generated />
namespace FanMatch.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddBannedAndLocked : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBannedAndLocked));
        
        string IMigrationMetadata.Id
        {
            get { return "201306151242077_AddBannedAndLocked"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
