// <auto-generated />
namespace FanMatch.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CanMatchMultiple : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CanMatchMultiple));
        
        string IMigrationMetadata.Id
        {
            get { return "201306151400478_CanMatchMultiple"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
